### ISSUE TITLE
exifread reaturn empty tags object

### ISSUE THREAD

**Issue by Nippey** [ianare/exif-py#35]
Hi,

I tried your ExifRead on my Synology on two different images, that both contain tags if read with exiftool.

What details can I provide you?

Linux Synology_NAS 3.2.40 #3810 SMP Wed Nov 6 05:13:41 CST 2013 armv7l GNU/Linux synology_armadaxp_ds214+

Python 3.3.2 (default, Dec 23 2013, 16:12:02)
[GCC 4.6.4] on linux

EXIF.py Ver 1.4.2

BR
Nippey

**Comment by irdroid3** [comment]
As a dumb user, here is a hint for other dumb users...
I also had the UnicodeDecodeError error -

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 668: character maps to <undefined>

This is because I passed the file object after doing -

f = open(join(dirName,fname))

Change this to -

f = open(join(dirName,fname),'rb')

and there is no decode performed !!!! - works for me now...

**Comment by irdroid3** [comment]
Weird - open the file (as above), then :-1: 
   exif = exifread.process_file(f)
The list of tags in the exif variable comes out in a different order each run...

**Comment by v-python** [comment]
On 4/22/2015 7:15 AM, irdroid3 wrote:
>
> Weird - open the file (as above), then :-1:
> exif = exifread.process_file(f)
> The list of tags in the exif variable comes out in a different order 
> each run...
>

That's because it isn't sorted, and Python hashes are randomized each 
run as a security measure against DoS attacks on servers.

Probably would be a reasonable idea for exifread to sort the output, 
which would make the order consistent.

**Comment by ianare** [comment]
There is a branch somewhat in progress that would arrange the output as a multidimensional list, for sorting and easier access. But this would break backwards compatibility, so would need to be made an option.
