### ISSUE TITLE
Non-image file formats do not work

### ISSUE THREAD

**Issue by alexforencich** [ianare/exif-py#39]
The MOV files from my 7d and the MP4, THM, and LRV files from my gopro all result in empty lists with no exceptions thrown.  Interestingly, the THM files from my 7d are fine.  All files tested are correctly read by exiftool.

**Comment by jxramos** [comment]
@alexforencich  `THM` files are actually jpg thumbnails I recently found out https://photo.stackexchange.com/a/5126/59229.

@ianare how would you feel about extending the lib to cover other media types? I'm not sure how canonical the mappings are between the tags for something like a MOV file or mp4 etc, eg do video file formats even recognize something like `EXIF DateTimeOriginal`?

I'd be down to contribute and poke around with this subject. I just started digging in this realm after facing trying to organize a ton of iphone images by original datetime--which unlike android OS doesn't timestamp their filenames so I need to go by exif data. Your library has helped tremendously for me to automate that work in python. I'm super glad I found you all also cover HEIC formats which I would have found out after the fact that those files got organized by download creation date rather than date taken. That's the essentially the problem with downloading icloud stuff, it's always considered a new file by the filesystem.

Either way thanks for the great library, have a good weekend.
